---
abstract: 'An EPP formatter for Number::Phone'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Number::Phone: '3.1'
  Socket: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.006, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Number-Phone-Formatter-EPP
requires:
  Number::Phone: '3.1'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Number-Phone-Formatter-EPP
  homepage: http://search.cpan.org/dist/Number-Phone-Formatter-EPP/
  repository: git://github.com/mschout/perl-number-phone-formatter-epp.git
version: '0.03'
x_serialization_backend: 'YAML::Tiny version 1.63'
